In [1]:
import numpy as np

## Aggregate Function

In [2]:
#aggregate along specific axis
mat = np.arange(1,16).reshape(3,5)
np.sum(mat)
print(np.sum(mat))
print(np.sum(mat, axis=0))
print(np.sum(mat, axis=1))
print(np.prod(mat)) #1*2*3*4....*15
print(np.prod(mat, axis=0))
print(np.prod(mat, axis=1))

120
[18 21 24 27 30]
[15 40 65]
1307674368000
[ 66 168 312 504 750]
[   120  30240 360360]


In [3]:
# Similar function names for array with missing values
arr = np.arange(1, 16, dtype=float)  #float is for the NaN in the next line
arr[-1] = np.NaN    # a given constant in numpy: similar to NoneType
print(arr)
print(np.sum(arr))  #won't run if there is NaN in the array
print(np.nansum(arr)) 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. nan]
nan
105.0
